#!/usr/bin/env node
"use strict";

// Bundle src/js entries into ../static (committed, embedded by Go).
const path = require("path");
const esbuild = require("esbuild");

const root = path.join(__dirname, "..");
const outDir = path.join(root, "..", "static");

esbuild
  .build({
    absWorkingDir: root,
    entryPoints: {
      app: "src/js/main.js",
      import: "src/js/import.js",
    },
    outdir: outDir,
    bundle: true,
    format: "iife",
    target: "es2022",
    // Keep //! comments: Go tests string-guard a few of them in /static/app.js.
    legalComments: "inline",
    banner: { js: "// Generated by ui/scripts/build-js.js from ui/src/js. Do not edit." },
    logLevel: "info",
  })
  .catch(() => process.exit(1));
