// Entry: bundled to internal/web/static/app.js (see ui/scripts/build-js.js).
import { bootTheme } from "./theme.js";
import { bootLanes } from "./lanes.js";
import { bootTaskrows } from "./taskrows.js";
import { bootMaintenance } from "./maintenance.js";
import { bootFieldInfo } from "./field_info.js";
import { bootFlash } from "./flash.js";
import { bootControls } from "./controls.js";
import { bootHooks } from "./hooks.js";
import { bootValidity } from "./validity.js";
import { bootAddSeries } from "./add_series.js";
import { bootListFilter } from "./list_filter.js";
import { bootNotes } from "./notes.js";
import { bootFormReset } from "./form_reset.js";
import { bootJoins } from "./joins.js";
import { bootSourceForms } from "./source_forms.js";
import { bootSettingsAutosave } from "./settings_autosave.js";
import { bootSeriesBulk } from "./series_bulk.js";
import { bootVideoBulk } from "./video_bulk.js";
import { bootFilesBulk } from "./files_bulk.js";
import { bootSourcesBulk } from "./sources_bulk.js";
import { bootNotificationsBulk } from "./notifications_bulk.js";
import { bootConfirmNotify } from "./confirm_notify.js";
import { bootListTable } from "./list_table.js";
import { bootListInfinite } from "./list_infinite.js";
import { bootLibraryTree } from "./library_tree.js";

bootTheme();
bootLanes();
bootTaskrows();
bootMaintenance();
bootFieldInfo();
bootFlash();
bootControls();
bootHooks();
bootValidity();
bootAddSeries();
bootListFilter();
bootNotes();
bootFormReset();
bootJoins();
bootSourceForms();
bootSettingsAutosave();
bootSeriesBulk();
bootVideoBulk();
bootFilesBulk();
bootSourcesBulk();
bootNotificationsBulk();
bootConfirmNotify();
bootListTable();
bootListInfinite();
bootLibraryTree();
